let skip_defaults_vim=1
set nocompatible
if empty("$XDG_CACHE_HOME")
    let $XDG_CACHE_HOME="$HOME/.cache"
endif

if empty("$XDG_CONFIG_HOME")
    let $XDG_CONFIG_HOME="$HOME/.config"
endif

if empty("$XDG_DATA_HOME")
    let $XDG_DATA_HOME="$HOME/.local/share"
endif

set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
exec "set viminfo=%,<800,'10,/50,:100,h,f0,n" .. $XDG_CACHE_HOME .. '/vim/viminfo'
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

set runtimepath^=$XDG_CONFIG_HOME/nvim runtimepath+=$XDG_CONFIG_HOME/nvim/after
let &packpath = &runtimepath
source $XDG_CONFIG_HOME/nvim/init.vim
